services:
    rosesyt:
        build: .
        image: rosesyt:latest
        container_name: rosesyt_container
        volumes:
            - ./static:/app/static
            - ./templates:/app/templates
        ports:
            - "5047:5047"
        environment:
            - FIXTURE_URL=${FIXTURE_URL}
